Nikhil2112
marlinprotocol/OpenWeaver pull request #83
Opened 2022-01-04 16:33 UTC by nikhilsamrat

Created a Map from clientKey to id

2022-01-10 11:37 UTC, roshanr95 requested changes

2022-01-10 11:37 UTC, roshanr95 commented on beacon/include/marlin/beacon/Grapher.hpp
> +	std::map< std::string, std::string> MData;
give a better name and in snake_case e.g. client_key_map

2022-01-10 11:37 UTC, roshanr95 commented on beacon/include/marlin/beacon/Grapher.hpp
> +	void query_cb() {
name it query_subgraph

2022-01-10 11:37 UTC, roshanr95 commented on beacon/include/marlin/beacon/Grapher.hpp
> +		t.template start<Grapher, &Grapher::query>(0, 3000000);
extra 0, should be 300k

2022-01-10 11:37 UTC, roshanr95 commented on beacon/include/marlin/beacon/ClusterDiscoverer.hpp
> +uint8_t* hextoint(std::string s){
add `static`

2022-01-10 11:37 UTC, roshanr95 commented on beacon/include/marlin/beacon/ClusterDiscoverer.hpp
> +	uint8_t* res = new uint8_t[(s.length()-2)*2];
memory leak here

2022-01-10 11:37 UTC, roshanr95 commented on beacon/include/marlin/beacon/Grapher.hpp
> +        uv_getaddrinfo_t* req = new uv_getaddrinfo_t();
memory leak here

2022-01-10 11:39 UTC, nikhilsamrat commented on beacon/include/marlin/beacon/Grapher.hpp
> +        uv_getaddrinfo_t* req = new uv_getaddrinfo_t();
That is required.

2022-01-10 11:56 UTC, nikhilsamrat commented on beacon/include/marlin/beacon/ClusterDiscoverer.hpp
> +	uint8_t* res = new uint8_t[(s.length()-2)*2];
resolved in next commit

2022-01-10 11:56 UTC, nikhilsamrat commented on beacon/include/marlin/beacon/ClusterDiscoverer.hpp
> +uint8_t* hextoint(std::string s){
resolved

2022-01-10 11:56 UTC, nikhilsamrat commented on beacon/include/marlin/beacon/Grapher.hpp
> +		t.template start<Grapher, &Grapher::query>(0, 3000000);
resolved in next commit

2022-01-10 11:57 UTC, nikhilsamrat commented on beacon/include/marlin/beacon/Grapher.hpp
> +	void query_cb() {
resolved in next commit

2022-01-10 12:17 UTC, nikhilsamrat commented on beacon/include/marlin/beacon/Grapher.hpp
> +        uv_getaddrinfo_t* req = new uv_getaddrinfo_t();
deleted in the callback

2022-01-17 07:14 UTC, roshanr95 approved these changes

2022-01-17 07:25 UTC, merged